<a href="https://colab.research.google.com/github/benniella/Ml-learning/blob/main/hatespeech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.impute import SimpleImputer

# New Section

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
import re
import nltk
from nltk.util import pr
stemmer = nltk.SnowballStemmer("english")
from nltk.corpus import stopwords
import string
stopword = set(stopwords.words("english"))

In [ ]:
df = pd.read_csv("twitter_data.csv")

print(df.head())

   Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2
1           1      3            0                   3        0      1
2           2      3            0                   3        0      1
3           3      3            0                   2        1      1
4           4      6            0                   6        0      1

                                               tweet
0  !!! RT @mayasolovely: As a woman you shouldn't...
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [ ]:
df['labels'] = df['class'].map({0:'Hate Speech Detected', 1:'Offensive language detected', 3:'No hate and offensive Speech'})
print(df.head())

   Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2
1           1      3            0                   3        0      1
2           2      3            0                   3        0      1
3           3      3            0                   2        1      1
4           4      6            0                   6        0      1

                                               tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

                        labels
0                          NaN
1  Offensive language detected
2  Offensive language detected
3  Offensive language detected
4  Offensive language detected

In [ ]:
df = df[['tweet', 'labels']]
df.head()

,tweet,labels
0,!!! RT @mayasolovely: As a woman you shouldn't...,NaN
1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,Offensive language detected
2,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,Offensive language detected
3,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,Offensive language detected
4,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,Offensive language detected

In [ ]:
df.dropna()

,tweet,labels
0,rt mayasolov woman shouldnt complain clean ho...,99999
1,rt boy dat coldtyga dwn bad cuffin dat hoe ...,Offensive language detected
2,rt urkindofbrand dawg rt ever fuck bitch sta...,Offensive language detected
3,rt cganderson vivabas look like tranni,Offensive language detected
4,rt shenikarobert shit hear might true might f...,Offensive language detected
...,...,...
24778,yous muthafin lie coreyemanuel right tl tras...,Offensive language detected
24779,youv gone broke wrong heart babi drove redneck...,99999
24780,young buck wanna eat dat nigguh like aint fuck...,Offensive language detected
24781,youu got wild bitch tellin lie,Offensive language detected
24782,ruffl ntac eileen dahlia beauti color combin...,99999

In [ ]:
def clean(text):

  text = str(text).lower()
  text = re.sub('\[.*?\]','', text)
  text = re.sub('https?://\S+|WWW\.\S+', '', text)
  text = re.sub('<.*?>+', '', text)
  text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
  text = re.sub('\n', '', text)
  text = re.sub('\w*\d\w*', '', text)
  text = [word for word in text.split(' ') if word not in stopword]
  text = " ".join(text)
  text = [stemmer.stem(word) for word in text.split(' ')]
  text =" ".join(text)
  return text

df["tweet"]= df["tweet"].apply(clean)

print(df.head())

                                               tweet  \
0   rt mayasolov woman shouldnt complain clean ho...
1   rt  boy dat coldtyga dwn bad cuffin dat hoe  ...
2   rt urkindofbrand dawg rt  ever fuck bitch sta...
3             rt cganderson vivabas look like tranni
4   rt shenikarobert shit hear might true might f...

                        labels
0                          NaN
1  Offensive language detected
2  Offensive language detected
3  Offensive language detected
4  Offensive language detected

In [ ]:
df = df.replace(99999, 'No Hate and Offensive Speech')

In [ ]:
x = np.array(df['tweet'])
y = np.array(df['labels'])

cv = CountVectorizer()
x = cv.fit_transform(x)
x_train, x_test,y_train, y_test = train_test_split(x,y, test_size=0.33, random_state= 42)
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
test_data = "i will kill you"
df = cv.transform([test_data]).toarray()
print(clf.predict(df))

['Hate Speech Detected']

In [ ]:
test_data = "you are awesome"
df = cv.transform([test_data]).toarray()
print(clf.predict(df))

['No Hate and Offensive Speech']